site_name: Yuzu resources
repo_url: https://github.com/yuzu-co/resources
site_author: Yuzu
pages:
- 'Index': 'index.md'
- 'Magento': 'magento.md'
- 'Prestashop': 'prestashop.md'
- 'Woocommerce': 'woocommerce.md'
- 'Bigcommerce': 'bigcommerce.md'
- 'Shopify': 'shopify.md'
theme: readthedocs