site_name: Yuzu resources
pages:
- [index.md, Index]
- [magento.md, Magento]
- [prestashop.md, Prestashop]
- [woocommerce.md, Woocommerce]
- [bigcommerce.md, Bigcommerce]
- [shopify.md, Shopify]
theme: readthedocs